### ISSUE TITLE
Bug: Total Products in Top Bar Component 

### ISSUE THREAD

**Issue by algnot** [ome-let/next-frontend-communication-system#11]
![image](https://github.com/ome-let/next-frontend-communication-system/assets/68460859/656c9f91-6c38-4077-a5c9-043d72a2962b)
- จากรูป total product ถูก hardcord ไว้ที่ 99999
- แก้ให้ component ดังกล่าวรับ props totalProduct เข้าไป
    - หากไม่ได้ส่งค่า totalProduct เข้าไป assume ว่าเป็น 0 ได้เลย

**Comment by khaimook134411** [comment]
completed
